# Generated by Django 4.2.3 on 2023-10-23 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_contactus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactUs",
        ),
    ]
